name:  $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)  

trigger:
- master

variables:
  StatefileContext : $(System.TeamProject)_$(Build.DefinitionName)_$(Build.Repository.Name)_$(Build.SourceBranchName)

stages:
- stage: CI
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Create build artifact'
    pool: 
      vmImage: 'windows-latest'
    steps:
    - publish: $(System.DefaultWorkingDirectory)
      artifact: drop

- stage: dev  
  variables:
    Subscription: AzureSp
    group: dev-variables
  displayName: 'deploy dev'
  jobs:
  - deployment: dev
    environment: dev
    pool: 
      vmImage: 'windows-latest'
    strategy: 
      runOnce:
        preDeploy:
          steps:
          - download: current
            artifact: drop

        deploy:
          steps:
          - template: templates/terraform-steps.yml
            parameters:
              backendServiceArm : $(Subscription)
              workingDirectory: $(Pipeline.Workspace)/drop
              backendAzureRmResourceGroupName: $(Tf.ResourceGroup)
              backendAzureRmStorageAccountName: $(Tf.StorageAccount)
              backendAzureRmContainerName: $(Tf.Container)
              environment: 'dev'
              statefileContext: $(StatefileContext)
 
- stage: test  
  variables:
    Subscription: AzureSp
    group: test-variables
  displayName: 'deploy test'
  jobs:  
  - deployment: test
    environment: test
    pool: 
      vmImage: 'windows-latest'
    strategy: 
      runOnce:
        preDeploy:
          steps:
          - download: current
            artifact: drop

        deploy:
          steps:
          - template: templates/terraform-steps.yml
            parameters:
              backendServiceArm : $(Subscription)
              workingDirectory: $(Pipeline.Workspace)/drop
              backendAzureRmResourceGroupName: $(Tf.ResourceGroup)
              backendAzureRmStorageAccountName: $(Tf.StorageAccount)
              backendAzureRmContainerName: $(Tf.Container)
              environment: 'test'
              statefileContext: $(StatefileContext)

- stage: prod  
  variables:
    Subscription: AzureSp
    group: prod-variables
  displayName: 'deploy prod'
  jobs:  
  - deployment: prod
    environment: prod
    pool: 
      vmImage: 'windows-latest'
    strategy: 
      runOnce:
        preDeploy:
          steps:
          - download: current
            artifact: drop

        deploy:
          steps:
          - template: templates/terraform-steps.yml
            parameters:
              backendServiceArm : $(Subscription)
              workingDirectory: $(Pipeline.Workspace)/drop
              backendAzureRmResourceGroupName: $(Tf.ResourceGroup)
              backendAzureRmStorageAccountName: $(Tf.StorageAccount)
              backendAzureRmContainerName: $(Tf.Container)
              environment: 'prod'
              statefileContext: $(StatefileContext)
