name:  $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)  

trigger:
- master


stages:
- stage: build
  displayName: 'build artifact'
  jobs:
  - job: Build
    displayName: 'Create build artifact'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - publish: $(System.DefaultWorkingDirectory)
      artifact: build
        
  - job: Deploy_dev
    dependsOn: Build
    displayName: 'Deploy to dev environment'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: build
