name:  $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)  

trigger:
- master

variables:
  Tf.Statefile : $(System.TeamProject)_$(Build.DefinitionName)_$(Build.Repository.Name)_$(Build.SourceBranchName)_terraform.tfstate
  Subscription : MSDN Enterprise
stages:
- stage: CI
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Create build artifact'
    pool: 'private'
    steps:
    - publish: $(System.DefaultWorkingDirectory)
      artifact: drop

- stage: CD  
  variables:
   - group: dev-variables
  displayName: 'Deploy'
  jobs:
  - deployment: Deploy
    environment: dev
    pool: 'private'
    strategy: 

      runOnce:
        preDeploy:
          steps:
          - download: current
            artifact: drop

        deploy:
        - template: templates/terraform-steps.yml
          parameters:
            backendServiceArm : $(Subscription)
            workingDirectory: $(Pipeline.Workspace)/drop
            backendAzureRmResourceGroupName: $(Tf.ResourceGroup)
            backendAzureRmStorageAccountName: $(Tf.StorageAccount)
            backendAzureRmContainerName: $(Tf.Container)
            backendAzureRmKey: $(Tf.Statefile)
            environment: 'dev'